### ISSUE TITLE
fzf-lua

### ISSUE THREAD

**Issue by M1Sports20** [tummetott/reticle.nvim#2]
I am using ibhagwan/fzf-lua with this plugin.  When I toggle the fzf menu the cursor row stays hidden for the rest of the life of the vim session.

Feel free to close, I haven't had time to further debug.  I just wanted to make you aware of it.

**Comment by tummetott** [comment]
Thank you for reporting this. I'm aware of the bug. It also happens with other plugins.

Some background information: This plugin tries to distinguish between cursorline changes made by the user (with e.g. `set cursorline`) and local cursorline changes made by plugins for their local windows. However, the distinction is not bullet proof since (n)vim does not offer a reliable way to achieve this. A solution would be to create a user command (like `:ReticleCursorlineToggle`) which wraps around the native vim command and updates the plugin state. I hesitated implementing it, because I thought I might come up with a better solution which would hook into vims native `set cursorline` command. I'm still thinking about it, but I'll promise I'll fix it soon.

**Comment by M1Sports20** [comment]
No rush.  I actually just tried switching to telescope and it seems to work okay with that.
