### ISSUE TITLE
[bug report] attempt to call global 'on_startup' (a nil value)

### ISSUE THREAD

**Issue by kohane27** [tummetott/reticle.nvim#5]
Hello there. Hope you're doing well. Thank you for creating handy plugin!

Please see below error when starting nvim:

```
Error detected while processing /home/username/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/username/.config/nvim/lua/plugins/reticle.lua:7: attempt to call global 'on_startup' (a nil value)
stack traceback:
        /home/username/.config/nvim/lua/plugins/reticle.lua:7: in main chunk
        [C]: in function 'require'
        /home/username/.config/nvim/init.lua:88: in main chunk
Press ENTER or type command to continue
```

`reticle.lua`:

```lua
require("reticle").setup({
  on_startup({
    cursorline = true,
    cursorcolumn = true,
  }),
})
```

My linter is warning me the following:

```
Undefined global `on_startup`. 7:3:1 Lua Diagnostics.undefined-global
```

Thanks again!

**Comment by tummetott** [comment]
Hello,

Thank you for your report and for using this plugin. 
The error you're encountering is due to a syntax issue in your configuration. The correct code should be as follows:

```lua
require("reticle").setup({
  on_startup = {
    cursorline = true,
    cursorcolumn = true,
  },
})
```

In the incorrect code you provided, you used parentheses for the `on_startup` table, which caused Lua to interpret it as a function call rather than a table assignment. That's why you're getting the "attempt to call global 'on_startup' (a nil value)" error.

By using `on_startup = {...}`, you correctly define a table inside the setup function, and your configuration should work as intended.

If you make this change and still encounter any issues, please don't hesitate to reach out for further assistance.

**Comment by kohane27** [comment]
Thank you so much for getting back to me on such short notice. And with such detailed explanation! Thank you!

I was looking into the cause of the syntax issue: I think there is a missing pair of `()` in [configuration](https://github.com/tummetott/reticle.nvim#%EF%B8%8F--configuration):

```lua
require('reticle').setup {
    -- Enable/Disable the cursorline and/or cursorcolumn at startup
    -- Default: false for both values
    on_startup {
        cursorline = false,
        cursorcolumn = false,
    }
}
```

and when I pasted it into the config lua file, my formatter caused below:

```lua
require("reticle").setup({
  -- Enable/Disable the cursorline and/or cursorcolumn at startup
  -- Default: false for both values
  on_startup({
    cursorline = false,
    cursorcolumn = false,
  }),
})
```

Regardless it should be an easy doc fix! Thank you again and have a good day!

**Comment by tummetott** [comment]
Ah you're right there is a `=` missing. The parenthesis are not needed for functions when there is a single table as argument. That's syntactic sugar of LUA
