### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by pkazmier** [tummetott/reticle.nvim#8]
Not an issue, just wanted to thank you as I was struggling all morning trying to achieve similar functionality, but couldn't figure out why `vim.bo.filetype` wasn't always set. I was going crazy! Then I discovered your plugin and happily ditched my auto commands for it.

I did notice that you use `vim.schedule` to delay, which seems to be the missing link that I was stumbling over. I read the documentation for `vim.schedule` but it was pretty lacking, so how did you know this was going to wait long enough for `vim.bo.filetype` to be set correctly?

In any case, thanks again for the handy plugin. I love it, but I really dislike seeing the cursor line in inactive windows as it's very hard for me to quickly identify my windows as the long, horizontal cursor line can look like a border.  Your plugin is exactly what I was looking for. Thanks!

**Comment by tummetott** [comment]
Thanks, i'm glad you like the plugin!

There are situations where the filetype of a buffer or window isn't set at the time your autocommand code runs. This is typically because these events can fire before Neovim has fully initialized the buffer's settings, including its filetype.

`vim.schedule()` is a function that schedules a Lua function to be called later, once Neovim returns to its event loop. This effectively defers the execution of your function until after the current event processing (including other autocommands) is complete, and Neovim has had an opportunity to fully initialize the buffer, including setting the filetype.

**Comment by pkazmier** [comment]
Thank you for explaining `vim.schedule()` to me. I understand now.
